#!/usr/bin/env node
if(global.TextEncoder === undefined){
    const { TextEncoder, TextDecoder } = require('util');
    global.TextEncoder = TextEncoder;
    global.TextDecoder = TextDecoder;
}
const limit = 743700
const Indexer = require('./indexer');
require('dotenv').config();
const mongo = require('mongoose');
const path = require('path');
const certPath = path.join(__dirname,'ca-certificate.crt');
mongo.connect(`${process.env.MONGO_URI}?authSource=admin&tls=true&tlsCAFile=${certPath}`,(err)=>{
    if(err)
        return console.log(err);
    return console.log("DB Connected!");
});
let indexer = new Indexer();

async function scan(){
    for(let i=0; i<=limit;i++){
        try{
            await indexer.getBlock(i);
        }catch(e){
            console.log(e);
        }
    }
}
