#!/usr/bin/env node
const TxnScanner = require('./txn-scanner');
const mongo = require('mongoose');
const path = require('path');
const certPath = path.join(__dirname,'ca-certificate.crt');
mongo.connect(`${process.env.MONGO_URI}?authSource=admin&tls=true&tlsCAFile=${certPath}`,(err)=>{
    if(err)
        return console.log(err);
    return console.log("DB Connected!");
});


let scanner = new TxnScanner(process.env.WS_LINK,process.env.RPC_LINK);
scanner.start();
